### ISSUE TITLE
Add loading module

### ISSUE THREAD

**Issue by getdave** [getdave/tanlinell-framework#10]
Add standard module. Currently demoed in CWD Layout A

``` scss
.loading:after,
.loading:before {
    content:"";
    position:absolute;
    z-index:10;
    display:block;
}

.loading:before {
    left:0;
    top:0;
    z-index: $zindex-tier-5;
    width:100%;
    height:100%;
    background:#444;
}

.loading:after {
    left:50%;
    top:50%;
    z-index: $zindex-tier-6;
    width:40px;
    height:40px;
    margin:-20px 0 0 -20px;
    background: image-url("ajax-loader--dark.gif") no-repeat 50% 50% #222;  
    opacity:0.25;
    border-radius:50%;
}
```
